import { AdminTableProps } from "./types";

export const adminDataTable: AdminTableProps[] = [
  {
    id: 93890,
    imgSrc: "/images/activity-2.png",
    name: "Nadine Bradtke",
    role: "Director",
    email: "VonRueden@gmail.com",
    status: "Active",
    phoneNumber: "+234 7061548319",
    username: "nadine",
    employeeId: "Colab12345",
    region: "Nigeria Lagos",
    departments: ["Visual Designer", "Interaction Designer"],
    location: "Africa/Lagos",
    timeZone: "11:50PM GMT+4",
    language: "English",
  },
  {
    id: 93891,
    imgSrc: "/images/activity-2.png",
    name: "Nadine Bradtke",
    role: "CEO",
    email: "VonRueden@gmail.com",
    status: "Suspended",
  },
  {
    id: 93892,
    imgSrc: "/images/activity-2.png",
    name: "Nadine Bradtke",
    role: "4 Permission",
    email: "VonRueden@gmail.com",
    status: "Suspended",
  },
  {
    id: 93893,
    imgSrc: "/images/activity-2.png",
    name: "Nadine Bradtke",
    role: "IT",
    email: "VonRueden@gmail.com",
    status: "Suspended",
  },
  {
    id: 93894,
    imgSrc: "/images/activity-2.png",
    name: "Nadine Bradtke",
    role: "Support",
    email: "VonRueden@gmail.com",
    status: "Active",
  },
  {
    id: 93895,
    imgSrc: "/images/activity-2.png",
    name: "Nadine Bradtke",
    role: "Support",
    email: "VonRueden@gmail.com",
    status: "Suspended",
  },
  {
    id: 93896,
    imgSrc: "/images/activity-2.png",
    name: "Nadine Bradtke",
    role: "Marketing",
    email: "VonRueden@gmail.com",
    status: "Suspended",
  },
  {
    id: 93897,
    imgSrc: "/images/activity-2.png",
    name: "Nadine Bradtke",
    role: "Marketing",
    email: "VonRueden@gmail.com",
    status: "Active",
  },
  {
    id: 93898,
    imgSrc: "/images/activity-2.png",
    name: "Nadine Bradtke",
    role: "CEO",
    email: "VonRueden@gmail.com",
    status: "Active",
  },
  {
    id: 93899,
    imgSrc: "/images/activity-2.png",
    name: "Nadine Bradtke",
    role: "Director",
    email: "VonRueden@gmail.com",
    status: "Suspended",
  },
];
